// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHv19IZzPf8pKLpv1vVoqRHcesCj4RoEE',
    appId: '1:664910367649:web:1084ab17378bc381bb99e0',
    messagingSenderId: '664910367649',
    projectId: 'pathoptimization',
    authDomain: 'pathoptimization.firebaseapp.com',
    storageBucket: 'pathoptimization.firebasestorage.app',
    measurementId: 'G-FHEV5WX64P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC8jNDxIZC8EaXamed4wRsofrvO80jJwg',
    appId: '1:664910367649:android:d74ce7a88fe05a33bb99e0',
    messagingSenderId: '664910367649',
    projectId: 'pathoptimization',
    storageBucket: 'pathoptimization.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYxw8UmY5VK1zsoPRF2WPtp0aKMLFwnAk',
    appId: '1:664910367649:ios:d928176c4df28b21bb99e0',
    messagingSenderId: '664910367649',
    projectId: 'pathoptimization',
    storageBucket: 'pathoptimization.firebasestorage.app',
    iosBundleId: 'com.example.pathOptimizeAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYxw8UmY5VK1zsoPRF2WPtp0aKMLFwnAk',
    appId: '1:664910367649:ios:d928176c4df28b21bb99e0',
    messagingSenderId: '664910367649',
    projectId: 'pathoptimization',
    storageBucket: 'pathoptimization.firebasestorage.app',
    iosBundleId: 'com.example.pathOptimizeAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHv19IZzPf8pKLpv1vVoqRHcesCj4RoEE',
    appId: '1:664910367649:web:9ae8bb70d1215f4dbb99e0',
    messagingSenderId: '664910367649',
    projectId: 'pathoptimization',
    authDomain: 'pathoptimization.firebaseapp.com',
    storageBucket: 'pathoptimization.firebasestorage.app',
    measurementId: 'G-8W2KE63DWH',
  );
}
